spring:
  application:
    name: email-sender
  mail:
    host: smtp.gmail.com
    username: ${gmail.username}  # your gmail username
    password: ${gmail.app.password}  # your gmail app password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
